comment:
  snippets:
    - id: comment
      files:
        - "*.html"
        - "**/*.html"
      body: |
        [Preview of this PR](https://htmlpreview.github.io/?https://github.com/nsrip-dd/nsrip-dd.github.io/blob/{{ GITHUB_HEAD_REF }}/index.html)
