name: PR previews

permissions:
  # The action wants to leave a comment on PRs
  pull-requests: write

on:
  pull_request:
    types: [opened, edited]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Generate preview link
        uses: exercism/pr-commenter-action@v1.5.1
